name: HangmanC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run cargo clippy
        run: cargo clippy --all-targets --all-features
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run cargo build
        run: cargo build --verbose

      - name: Run cargo test
        run: cargo test --verbose
      